// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ledger/v1/audit.proto

package ledgerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/use-fabrica/ledger/proto/ledger/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuditServiceName is the fully-qualified name of the AuditService service.
	AuditServiceName = "ledger.v1.AuditService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuditServiceListEntriesProcedure is the fully-qualified name of the AuditService's ListEntries
	// RPC.
	AuditServiceListEntriesProcedure = "/ledger.v1.AuditService/ListEntries"
	// AuditServiceListWalletTransactionsProcedure is the fully-qualified name of the AuditService's
	// ListWalletTransactions RPC.
	AuditServiceListWalletTransactionsProcedure = "/ledger.v1.AuditService/ListWalletTransactions"
	// AuditServiceGetTransactionByIdempotencyKeyProcedure is the fully-qualified name of the
	// AuditService's GetTransactionByIdempotencyKey RPC.
	AuditServiceGetTransactionByIdempotencyKeyProcedure = "/ledger.v1.AuditService/GetTransactionByIdempotencyKey"
	// AuditServiceGetTransactionByReferenceProcedure is the fully-qualified name of the AuditService's
	// GetTransactionByReference RPC.
	AuditServiceGetTransactionByReferenceProcedure = "/ledger.v1.AuditService/GetTransactionByReference"
)

// AuditServiceClient is a client for the ledger.v1.AuditService service.
type AuditServiceClient interface {
	ListEntries(context.Context, *connect.Request[v1.ListEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error)
	ListWalletTransactions(context.Context, *connect.Request[v1.ListWalletTransactionsRequest]) (*connect.Response[v1.ListWalletTransactionsResponse], error)
	GetTransactionByIdempotencyKey(context.Context, *connect.Request[v1.GetTransactionByIdempotencyKeyRequest]) (*connect.Response[v1.Transaction], error)
	GetTransactionByReference(context.Context, *connect.Request[v1.GetTransactionByReferenceRequest]) (*connect.Response[v1.Transaction], error)
}

// NewAuditServiceClient constructs a client for the ledger.v1.AuditService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuditServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuditServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	auditServiceMethods := v1.File_ledger_v1_audit_proto.Services().ByName("AuditService").Methods()
	return &auditServiceClient{
		listEntries: connect.NewClient[v1.ListEntriesRequest, v1.ListEntriesResponse](
			httpClient,
			baseURL+AuditServiceListEntriesProcedure,
			connect.WithSchema(auditServiceMethods.ByName("ListEntries")),
			connect.WithClientOptions(opts...),
		),
		listWalletTransactions: connect.NewClient[v1.ListWalletTransactionsRequest, v1.ListWalletTransactionsResponse](
			httpClient,
			baseURL+AuditServiceListWalletTransactionsProcedure,
			connect.WithSchema(auditServiceMethods.ByName("ListWalletTransactions")),
			connect.WithClientOptions(opts...),
		),
		getTransactionByIdempotencyKey: connect.NewClient[v1.GetTransactionByIdempotencyKeyRequest, v1.Transaction](
			httpClient,
			baseURL+AuditServiceGetTransactionByIdempotencyKeyProcedure,
			connect.WithSchema(auditServiceMethods.ByName("GetTransactionByIdempotencyKey")),
			connect.WithClientOptions(opts...),
		),
		getTransactionByReference: connect.NewClient[v1.GetTransactionByReferenceRequest, v1.Transaction](
			httpClient,
			baseURL+AuditServiceGetTransactionByReferenceProcedure,
			connect.WithSchema(auditServiceMethods.ByName("GetTransactionByReference")),
			connect.WithClientOptions(opts...),
		),
	}
}

// auditServiceClient implements AuditServiceClient.
type auditServiceClient struct {
	listEntries                    *connect.Client[v1.ListEntriesRequest, v1.ListEntriesResponse]
	listWalletTransactions         *connect.Client[v1.ListWalletTransactionsRequest, v1.ListWalletTransactionsResponse]
	getTransactionByIdempotencyKey *connect.Client[v1.GetTransactionByIdempotencyKeyRequest, v1.Transaction]
	getTransactionByReference      *connect.Client[v1.GetTransactionByReferenceRequest, v1.Transaction]
}

// ListEntries calls ledger.v1.AuditService.ListEntries.
func (c *auditServiceClient) ListEntries(ctx context.Context, req *connect.Request[v1.ListEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error) {
	return c.listEntries.CallUnary(ctx, req)
}

// ListWalletTransactions calls ledger.v1.AuditService.ListWalletTransactions.
func (c *auditServiceClient) ListWalletTransactions(ctx context.Context, req *connect.Request[v1.ListWalletTransactionsRequest]) (*connect.Response[v1.ListWalletTransactionsResponse], error) {
	return c.listWalletTransactions.CallUnary(ctx, req)
}

// GetTransactionByIdempotencyKey calls ledger.v1.AuditService.GetTransactionByIdempotencyKey.
func (c *auditServiceClient) GetTransactionByIdempotencyKey(ctx context.Context, req *connect.Request[v1.GetTransactionByIdempotencyKeyRequest]) (*connect.Response[v1.Transaction], error) {
	return c.getTransactionByIdempotencyKey.CallUnary(ctx, req)
}

// GetTransactionByReference calls ledger.v1.AuditService.GetTransactionByReference.
func (c *auditServiceClient) GetTransactionByReference(ctx context.Context, req *connect.Request[v1.GetTransactionByReferenceRequest]) (*connect.Response[v1.Transaction], error) {
	return c.getTransactionByReference.CallUnary(ctx, req)
}

// AuditServiceHandler is an implementation of the ledger.v1.AuditService service.
type AuditServiceHandler interface {
	ListEntries(context.Context, *connect.Request[v1.ListEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error)
	ListWalletTransactions(context.Context, *connect.Request[v1.ListWalletTransactionsRequest]) (*connect.Response[v1.ListWalletTransactionsResponse], error)
	GetTransactionByIdempotencyKey(context.Context, *connect.Request[v1.GetTransactionByIdempotencyKeyRequest]) (*connect.Response[v1.Transaction], error)
	GetTransactionByReference(context.Context, *connect.Request[v1.GetTransactionByReferenceRequest]) (*connect.Response[v1.Transaction], error)
}

// NewAuditServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuditServiceHandler(svc AuditServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	auditServiceMethods := v1.File_ledger_v1_audit_proto.Services().ByName("AuditService").Methods()
	auditServiceListEntriesHandler := connect.NewUnaryHandler(
		AuditServiceListEntriesProcedure,
		svc.ListEntries,
		connect.WithSchema(auditServiceMethods.ByName("ListEntries")),
		connect.WithHandlerOptions(opts...),
	)
	auditServiceListWalletTransactionsHandler := connect.NewUnaryHandler(
		AuditServiceListWalletTransactionsProcedure,
		svc.ListWalletTransactions,
		connect.WithSchema(auditServiceMethods.ByName("ListWalletTransactions")),
		connect.WithHandlerOptions(opts...),
	)
	auditServiceGetTransactionByIdempotencyKeyHandler := connect.NewUnaryHandler(
		AuditServiceGetTransactionByIdempotencyKeyProcedure,
		svc.GetTransactionByIdempotencyKey,
		connect.WithSchema(auditServiceMethods.ByName("GetTransactionByIdempotencyKey")),
		connect.WithHandlerOptions(opts...),
	)
	auditServiceGetTransactionByReferenceHandler := connect.NewUnaryHandler(
		AuditServiceGetTransactionByReferenceProcedure,
		svc.GetTransactionByReference,
		connect.WithSchema(auditServiceMethods.ByName("GetTransactionByReference")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ledger.v1.AuditService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuditServiceListEntriesProcedure:
			auditServiceListEntriesHandler.ServeHTTP(w, r)
		case AuditServiceListWalletTransactionsProcedure:
			auditServiceListWalletTransactionsHandler.ServeHTTP(w, r)
		case AuditServiceGetTransactionByIdempotencyKeyProcedure:
			auditServiceGetTransactionByIdempotencyKeyHandler.ServeHTTP(w, r)
		case AuditServiceGetTransactionByReferenceProcedure:
			auditServiceGetTransactionByReferenceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuditServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuditServiceHandler struct{}

func (UnimplementedAuditServiceHandler) ListEntries(context.Context, *connect.Request[v1.ListEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.AuditService.ListEntries is not implemented"))
}

func (UnimplementedAuditServiceHandler) ListWalletTransactions(context.Context, *connect.Request[v1.ListWalletTransactionsRequest]) (*connect.Response[v1.ListWalletTransactionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.AuditService.ListWalletTransactions is not implemented"))
}

func (UnimplementedAuditServiceHandler) GetTransactionByIdempotencyKey(context.Context, *connect.Request[v1.GetTransactionByIdempotencyKeyRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.AuditService.GetTransactionByIdempotencyKey is not implemented"))
}

func (UnimplementedAuditServiceHandler) GetTransactionByReference(context.Context, *connect.Request[v1.GetTransactionByReferenceRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.AuditService.GetTransactionByReference is not implemented"))
}
