// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ledger/v1/health.proto

package ledgerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/use-fabrica/ledger/proto/ledger/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HealthServiceName is the fully-qualified name of the HealthService service.
	HealthServiceName = "ledger.v1.HealthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HealthServiceCheckLivenessProcedure is the fully-qualified name of the HealthService's
	// CheckLiveness RPC.
	HealthServiceCheckLivenessProcedure = "/ledger.v1.HealthService/CheckLiveness"
	// HealthServiceCheckReadinessProcedure is the fully-qualified name of the HealthService's
	// CheckReadiness RPC.
	HealthServiceCheckReadinessProcedure = "/ledger.v1.HealthService/CheckReadiness"
)

// HealthServiceClient is a client for the ledger.v1.HealthService service.
type HealthServiceClient interface {
	CheckLiveness(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthCheckResponse], error)
	CheckReadiness(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthCheckResponse], error)
}

// NewHealthServiceClient constructs a client for the ledger.v1.HealthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHealthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HealthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	healthServiceMethods := v1.File_ledger_v1_health_proto.Services().ByName("HealthService").Methods()
	return &healthServiceClient{
		checkLiveness: connect.NewClient[emptypb.Empty, v1.HealthCheckResponse](
			httpClient,
			baseURL+HealthServiceCheckLivenessProcedure,
			connect.WithSchema(healthServiceMethods.ByName("CheckLiveness")),
			connect.WithClientOptions(opts...),
		),
		checkReadiness: connect.NewClient[emptypb.Empty, v1.HealthCheckResponse](
			httpClient,
			baseURL+HealthServiceCheckReadinessProcedure,
			connect.WithSchema(healthServiceMethods.ByName("CheckReadiness")),
			connect.WithClientOptions(opts...),
		),
	}
}

// healthServiceClient implements HealthServiceClient.
type healthServiceClient struct {
	checkLiveness  *connect.Client[emptypb.Empty, v1.HealthCheckResponse]
	checkReadiness *connect.Client[emptypb.Empty, v1.HealthCheckResponse]
}

// CheckLiveness calls ledger.v1.HealthService.CheckLiveness.
func (c *healthServiceClient) CheckLiveness(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthCheckResponse], error) {
	return c.checkLiveness.CallUnary(ctx, req)
}

// CheckReadiness calls ledger.v1.HealthService.CheckReadiness.
func (c *healthServiceClient) CheckReadiness(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthCheckResponse], error) {
	return c.checkReadiness.CallUnary(ctx, req)
}

// HealthServiceHandler is an implementation of the ledger.v1.HealthService service.
type HealthServiceHandler interface {
	CheckLiveness(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthCheckResponse], error)
	CheckReadiness(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthCheckResponse], error)
}

// NewHealthServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHealthServiceHandler(svc HealthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	healthServiceMethods := v1.File_ledger_v1_health_proto.Services().ByName("HealthService").Methods()
	healthServiceCheckLivenessHandler := connect.NewUnaryHandler(
		HealthServiceCheckLivenessProcedure,
		svc.CheckLiveness,
		connect.WithSchema(healthServiceMethods.ByName("CheckLiveness")),
		connect.WithHandlerOptions(opts...),
	)
	healthServiceCheckReadinessHandler := connect.NewUnaryHandler(
		HealthServiceCheckReadinessProcedure,
		svc.CheckReadiness,
		connect.WithSchema(healthServiceMethods.ByName("CheckReadiness")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ledger.v1.HealthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HealthServiceCheckLivenessProcedure:
			healthServiceCheckLivenessHandler.ServeHTTP(w, r)
		case HealthServiceCheckReadinessProcedure:
			healthServiceCheckReadinessHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHealthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthServiceHandler struct{}

func (UnimplementedHealthServiceHandler) CheckLiveness(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.HealthService.CheckLiveness is not implemented"))
}

func (UnimplementedHealthServiceHandler) CheckReadiness(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.HealthService.CheckReadiness is not implemented"))
}
