// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ledger/v1/posting.proto

package ledgerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/use-fabrica/ledger/proto/ledger/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PostingServiceName is the fully-qualified name of the PostingService service.
	PostingServiceName = "ledger.v1.PostingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PostingServiceCreateTransactionProcedure is the fully-qualified name of the PostingService's
	// CreateTransaction RPC.
	PostingServiceCreateTransactionProcedure = "/ledger.v1.PostingService/CreateTransaction"
	// PostingServiceCreatePendingTransactionProcedure is the fully-qualified name of the
	// PostingService's CreatePendingTransaction RPC.
	PostingServiceCreatePendingTransactionProcedure = "/ledger.v1.PostingService/CreatePendingTransaction"
	// PostingServicePostTransactionProcedure is the fully-qualified name of the PostingService's
	// PostTransaction RPC.
	PostingServicePostTransactionProcedure = "/ledger.v1.PostingService/PostTransaction"
	// PostingServiceVoidTransactionProcedure is the fully-qualified name of the PostingService's
	// VoidTransaction RPC.
	PostingServiceVoidTransactionProcedure = "/ledger.v1.PostingService/VoidTransaction"
	// PostingServiceGetTransactionProcedure is the fully-qualified name of the PostingService's
	// GetTransaction RPC.
	PostingServiceGetTransactionProcedure = "/ledger.v1.PostingService/GetTransaction"
)

// PostingServiceClient is a client for the ledger.v1.PostingService service.
type PostingServiceClient interface {
	CreateTransaction(context.Context, *connect.Request[v1.CreateTransactionRequest]) (*connect.Response[v1.Transaction], error)
	CreatePendingTransaction(context.Context, *connect.Request[v1.CreatePendingTransactionRequest]) (*connect.Response[v1.Transaction], error)
	PostTransaction(context.Context, *connect.Request[v1.PostTransactionRequest]) (*connect.Response[v1.Transaction], error)
	VoidTransaction(context.Context, *connect.Request[v1.VoidTransactionRequest]) (*connect.Response[v1.Transaction], error)
	GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error)
}

// NewPostingServiceClient constructs a client for the ledger.v1.PostingService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPostingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PostingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	postingServiceMethods := v1.File_ledger_v1_posting_proto.Services().ByName("PostingService").Methods()
	return &postingServiceClient{
		createTransaction: connect.NewClient[v1.CreateTransactionRequest, v1.Transaction](
			httpClient,
			baseURL+PostingServiceCreateTransactionProcedure,
			connect.WithSchema(postingServiceMethods.ByName("CreateTransaction")),
			connect.WithClientOptions(opts...),
		),
		createPendingTransaction: connect.NewClient[v1.CreatePendingTransactionRequest, v1.Transaction](
			httpClient,
			baseURL+PostingServiceCreatePendingTransactionProcedure,
			connect.WithSchema(postingServiceMethods.ByName("CreatePendingTransaction")),
			connect.WithClientOptions(opts...),
		),
		postTransaction: connect.NewClient[v1.PostTransactionRequest, v1.Transaction](
			httpClient,
			baseURL+PostingServicePostTransactionProcedure,
			connect.WithSchema(postingServiceMethods.ByName("PostTransaction")),
			connect.WithClientOptions(opts...),
		),
		voidTransaction: connect.NewClient[v1.VoidTransactionRequest, v1.Transaction](
			httpClient,
			baseURL+PostingServiceVoidTransactionProcedure,
			connect.WithSchema(postingServiceMethods.ByName("VoidTransaction")),
			connect.WithClientOptions(opts...),
		),
		getTransaction: connect.NewClient[v1.GetTransactionRequest, v1.Transaction](
			httpClient,
			baseURL+PostingServiceGetTransactionProcedure,
			connect.WithSchema(postingServiceMethods.ByName("GetTransaction")),
			connect.WithClientOptions(opts...),
		),
	}
}

// postingServiceClient implements PostingServiceClient.
type postingServiceClient struct {
	createTransaction        *connect.Client[v1.CreateTransactionRequest, v1.Transaction]
	createPendingTransaction *connect.Client[v1.CreatePendingTransactionRequest, v1.Transaction]
	postTransaction          *connect.Client[v1.PostTransactionRequest, v1.Transaction]
	voidTransaction          *connect.Client[v1.VoidTransactionRequest, v1.Transaction]
	getTransaction           *connect.Client[v1.GetTransactionRequest, v1.Transaction]
}

// CreateTransaction calls ledger.v1.PostingService.CreateTransaction.
func (c *postingServiceClient) CreateTransaction(ctx context.Context, req *connect.Request[v1.CreateTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return c.createTransaction.CallUnary(ctx, req)
}

// CreatePendingTransaction calls ledger.v1.PostingService.CreatePendingTransaction.
func (c *postingServiceClient) CreatePendingTransaction(ctx context.Context, req *connect.Request[v1.CreatePendingTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return c.createPendingTransaction.CallUnary(ctx, req)
}

// PostTransaction calls ledger.v1.PostingService.PostTransaction.
func (c *postingServiceClient) PostTransaction(ctx context.Context, req *connect.Request[v1.PostTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return c.postTransaction.CallUnary(ctx, req)
}

// VoidTransaction calls ledger.v1.PostingService.VoidTransaction.
func (c *postingServiceClient) VoidTransaction(ctx context.Context, req *connect.Request[v1.VoidTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return c.voidTransaction.CallUnary(ctx, req)
}

// GetTransaction calls ledger.v1.PostingService.GetTransaction.
func (c *postingServiceClient) GetTransaction(ctx context.Context, req *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return c.getTransaction.CallUnary(ctx, req)
}

// PostingServiceHandler is an implementation of the ledger.v1.PostingService service.
type PostingServiceHandler interface {
	CreateTransaction(context.Context, *connect.Request[v1.CreateTransactionRequest]) (*connect.Response[v1.Transaction], error)
	CreatePendingTransaction(context.Context, *connect.Request[v1.CreatePendingTransactionRequest]) (*connect.Response[v1.Transaction], error)
	PostTransaction(context.Context, *connect.Request[v1.PostTransactionRequest]) (*connect.Response[v1.Transaction], error)
	VoidTransaction(context.Context, *connect.Request[v1.VoidTransactionRequest]) (*connect.Response[v1.Transaction], error)
	GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error)
}

// NewPostingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPostingServiceHandler(svc PostingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	postingServiceMethods := v1.File_ledger_v1_posting_proto.Services().ByName("PostingService").Methods()
	postingServiceCreateTransactionHandler := connect.NewUnaryHandler(
		PostingServiceCreateTransactionProcedure,
		svc.CreateTransaction,
		connect.WithSchema(postingServiceMethods.ByName("CreateTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	postingServiceCreatePendingTransactionHandler := connect.NewUnaryHandler(
		PostingServiceCreatePendingTransactionProcedure,
		svc.CreatePendingTransaction,
		connect.WithSchema(postingServiceMethods.ByName("CreatePendingTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	postingServicePostTransactionHandler := connect.NewUnaryHandler(
		PostingServicePostTransactionProcedure,
		svc.PostTransaction,
		connect.WithSchema(postingServiceMethods.ByName("PostTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	postingServiceVoidTransactionHandler := connect.NewUnaryHandler(
		PostingServiceVoidTransactionProcedure,
		svc.VoidTransaction,
		connect.WithSchema(postingServiceMethods.ByName("VoidTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	postingServiceGetTransactionHandler := connect.NewUnaryHandler(
		PostingServiceGetTransactionProcedure,
		svc.GetTransaction,
		connect.WithSchema(postingServiceMethods.ByName("GetTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ledger.v1.PostingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PostingServiceCreateTransactionProcedure:
			postingServiceCreateTransactionHandler.ServeHTTP(w, r)
		case PostingServiceCreatePendingTransactionProcedure:
			postingServiceCreatePendingTransactionHandler.ServeHTTP(w, r)
		case PostingServicePostTransactionProcedure:
			postingServicePostTransactionHandler.ServeHTTP(w, r)
		case PostingServiceVoidTransactionProcedure:
			postingServiceVoidTransactionHandler.ServeHTTP(w, r)
		case PostingServiceGetTransactionProcedure:
			postingServiceGetTransactionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPostingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPostingServiceHandler struct{}

func (UnimplementedPostingServiceHandler) CreateTransaction(context.Context, *connect.Request[v1.CreateTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.PostingService.CreateTransaction is not implemented"))
}

func (UnimplementedPostingServiceHandler) CreatePendingTransaction(context.Context, *connect.Request[v1.CreatePendingTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.PostingService.CreatePendingTransaction is not implemented"))
}

func (UnimplementedPostingServiceHandler) PostTransaction(context.Context, *connect.Request[v1.PostTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.PostingService.PostTransaction is not implemented"))
}

func (UnimplementedPostingServiceHandler) VoidTransaction(context.Context, *connect.Request[v1.VoidTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.PostingService.VoidTransaction is not implemented"))
}

func (UnimplementedPostingServiceHandler) GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.PostingService.GetTransaction is not implemented"))
}
