// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ledger/v1/provisioning.proto

package ledgerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/use-fabrica/ledger/proto/ledger/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProvisioningServiceName is the fully-qualified name of the ProvisioningService service.
	ProvisioningServiceName = "ledger.v1.ProvisioningService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProvisioningServiceCreateAssetProcedure is the fully-qualified name of the ProvisioningService's
	// CreateAsset RPC.
	ProvisioningServiceCreateAssetProcedure = "/ledger.v1.ProvisioningService/CreateAsset"
	// ProvisioningServiceListAssetsProcedure is the fully-qualified name of the ProvisioningService's
	// ListAssets RPC.
	ProvisioningServiceListAssetsProcedure = "/ledger.v1.ProvisioningService/ListAssets"
	// ProvisioningServiceCreateHolderProcedure is the fully-qualified name of the ProvisioningService's
	// CreateHolder RPC.
	ProvisioningServiceCreateHolderProcedure = "/ledger.v1.ProvisioningService/CreateHolder"
	// ProvisioningServiceCreateWalletProcedure is the fully-qualified name of the ProvisioningService's
	// CreateWallet RPC.
	ProvisioningServiceCreateWalletProcedure = "/ledger.v1.ProvisioningService/CreateWallet"
	// ProvisioningServiceCreateAccountProcedure is the fully-qualified name of the
	// ProvisioningService's CreateAccount RPC.
	ProvisioningServiceCreateAccountProcedure = "/ledger.v1.ProvisioningService/CreateAccount"
	// ProvisioningServiceGetWalletBalancesProcedure is the fully-qualified name of the
	// ProvisioningService's GetWalletBalances RPC.
	ProvisioningServiceGetWalletBalancesProcedure = "/ledger.v1.ProvisioningService/GetWalletBalances"
)

// ProvisioningServiceClient is a client for the ledger.v1.ProvisioningService service.
type ProvisioningServiceClient interface {
	CreateAsset(context.Context, *connect.Request[v1.CreateAssetRequest]) (*connect.Response[v1.Asset], error)
	ListAssets(context.Context, *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error)
	CreateHolder(context.Context, *connect.Request[v1.CreateHolderRequest]) (*connect.Response[v1.Holder], error)
	CreateWallet(context.Context, *connect.Request[v1.CreateWalletRequest]) (*connect.Response[v1.Wallet], error)
	CreateAccount(context.Context, *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.Account], error)
	GetWalletBalances(context.Context, *connect.Request[v1.GetWalletBalancesRequest]) (*connect.Response[v1.GetWalletBalancesResponse], error)
}

// NewProvisioningServiceClient constructs a client for the ledger.v1.ProvisioningService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProvisioningServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProvisioningServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	provisioningServiceMethods := v1.File_ledger_v1_provisioning_proto.Services().ByName("ProvisioningService").Methods()
	return &provisioningServiceClient{
		createAsset: connect.NewClient[v1.CreateAssetRequest, v1.Asset](
			httpClient,
			baseURL+ProvisioningServiceCreateAssetProcedure,
			connect.WithSchema(provisioningServiceMethods.ByName("CreateAsset")),
			connect.WithClientOptions(opts...),
		),
		listAssets: connect.NewClient[v1.ListAssetsRequest, v1.ListAssetsResponse](
			httpClient,
			baseURL+ProvisioningServiceListAssetsProcedure,
			connect.WithSchema(provisioningServiceMethods.ByName("ListAssets")),
			connect.WithClientOptions(opts...),
		),
		createHolder: connect.NewClient[v1.CreateHolderRequest, v1.Holder](
			httpClient,
			baseURL+ProvisioningServiceCreateHolderProcedure,
			connect.WithSchema(provisioningServiceMethods.ByName("CreateHolder")),
			connect.WithClientOptions(opts...),
		),
		createWallet: connect.NewClient[v1.CreateWalletRequest, v1.Wallet](
			httpClient,
			baseURL+ProvisioningServiceCreateWalletProcedure,
			connect.WithSchema(provisioningServiceMethods.ByName("CreateWallet")),
			connect.WithClientOptions(opts...),
		),
		createAccount: connect.NewClient[v1.CreateAccountRequest, v1.Account](
			httpClient,
			baseURL+ProvisioningServiceCreateAccountProcedure,
			connect.WithSchema(provisioningServiceMethods.ByName("CreateAccount")),
			connect.WithClientOptions(opts...),
		),
		getWalletBalances: connect.NewClient[v1.GetWalletBalancesRequest, v1.GetWalletBalancesResponse](
			httpClient,
			baseURL+ProvisioningServiceGetWalletBalancesProcedure,
			connect.WithSchema(provisioningServiceMethods.ByName("GetWalletBalances")),
			connect.WithClientOptions(opts...),
		),
	}
}

// provisioningServiceClient implements ProvisioningServiceClient.
type provisioningServiceClient struct {
	createAsset       *connect.Client[v1.CreateAssetRequest, v1.Asset]
	listAssets        *connect.Client[v1.ListAssetsRequest, v1.ListAssetsResponse]
	createHolder      *connect.Client[v1.CreateHolderRequest, v1.Holder]
	createWallet      *connect.Client[v1.CreateWalletRequest, v1.Wallet]
	createAccount     *connect.Client[v1.CreateAccountRequest, v1.Account]
	getWalletBalances *connect.Client[v1.GetWalletBalancesRequest, v1.GetWalletBalancesResponse]
}

// CreateAsset calls ledger.v1.ProvisioningService.CreateAsset.
func (c *provisioningServiceClient) CreateAsset(ctx context.Context, req *connect.Request[v1.CreateAssetRequest]) (*connect.Response[v1.Asset], error) {
	return c.createAsset.CallUnary(ctx, req)
}

// ListAssets calls ledger.v1.ProvisioningService.ListAssets.
func (c *provisioningServiceClient) ListAssets(ctx context.Context, req *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error) {
	return c.listAssets.CallUnary(ctx, req)
}

// CreateHolder calls ledger.v1.ProvisioningService.CreateHolder.
func (c *provisioningServiceClient) CreateHolder(ctx context.Context, req *connect.Request[v1.CreateHolderRequest]) (*connect.Response[v1.Holder], error) {
	return c.createHolder.CallUnary(ctx, req)
}

// CreateWallet calls ledger.v1.ProvisioningService.CreateWallet.
func (c *provisioningServiceClient) CreateWallet(ctx context.Context, req *connect.Request[v1.CreateWalletRequest]) (*connect.Response[v1.Wallet], error) {
	return c.createWallet.CallUnary(ctx, req)
}

// CreateAccount calls ledger.v1.ProvisioningService.CreateAccount.
func (c *provisioningServiceClient) CreateAccount(ctx context.Context, req *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.Account], error) {
	return c.createAccount.CallUnary(ctx, req)
}

// GetWalletBalances calls ledger.v1.ProvisioningService.GetWalletBalances.
func (c *provisioningServiceClient) GetWalletBalances(ctx context.Context, req *connect.Request[v1.GetWalletBalancesRequest]) (*connect.Response[v1.GetWalletBalancesResponse], error) {
	return c.getWalletBalances.CallUnary(ctx, req)
}

// ProvisioningServiceHandler is an implementation of the ledger.v1.ProvisioningService service.
type ProvisioningServiceHandler interface {
	CreateAsset(context.Context, *connect.Request[v1.CreateAssetRequest]) (*connect.Response[v1.Asset], error)
	ListAssets(context.Context, *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error)
	CreateHolder(context.Context, *connect.Request[v1.CreateHolderRequest]) (*connect.Response[v1.Holder], error)
	CreateWallet(context.Context, *connect.Request[v1.CreateWalletRequest]) (*connect.Response[v1.Wallet], error)
	CreateAccount(context.Context, *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.Account], error)
	GetWalletBalances(context.Context, *connect.Request[v1.GetWalletBalancesRequest]) (*connect.Response[v1.GetWalletBalancesResponse], error)
}

// NewProvisioningServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProvisioningServiceHandler(svc ProvisioningServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	provisioningServiceMethods := v1.File_ledger_v1_provisioning_proto.Services().ByName("ProvisioningService").Methods()
	provisioningServiceCreateAssetHandler := connect.NewUnaryHandler(
		ProvisioningServiceCreateAssetProcedure,
		svc.CreateAsset,
		connect.WithSchema(provisioningServiceMethods.ByName("CreateAsset")),
		connect.WithHandlerOptions(opts...),
	)
	provisioningServiceListAssetsHandler := connect.NewUnaryHandler(
		ProvisioningServiceListAssetsProcedure,
		svc.ListAssets,
		connect.WithSchema(provisioningServiceMethods.ByName("ListAssets")),
		connect.WithHandlerOptions(opts...),
	)
	provisioningServiceCreateHolderHandler := connect.NewUnaryHandler(
		ProvisioningServiceCreateHolderProcedure,
		svc.CreateHolder,
		connect.WithSchema(provisioningServiceMethods.ByName("CreateHolder")),
		connect.WithHandlerOptions(opts...),
	)
	provisioningServiceCreateWalletHandler := connect.NewUnaryHandler(
		ProvisioningServiceCreateWalletProcedure,
		svc.CreateWallet,
		connect.WithSchema(provisioningServiceMethods.ByName("CreateWallet")),
		connect.WithHandlerOptions(opts...),
	)
	provisioningServiceCreateAccountHandler := connect.NewUnaryHandler(
		ProvisioningServiceCreateAccountProcedure,
		svc.CreateAccount,
		connect.WithSchema(provisioningServiceMethods.ByName("CreateAccount")),
		connect.WithHandlerOptions(opts...),
	)
	provisioningServiceGetWalletBalancesHandler := connect.NewUnaryHandler(
		ProvisioningServiceGetWalletBalancesProcedure,
		svc.GetWalletBalances,
		connect.WithSchema(provisioningServiceMethods.ByName("GetWalletBalances")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ledger.v1.ProvisioningService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProvisioningServiceCreateAssetProcedure:
			provisioningServiceCreateAssetHandler.ServeHTTP(w, r)
		case ProvisioningServiceListAssetsProcedure:
			provisioningServiceListAssetsHandler.ServeHTTP(w, r)
		case ProvisioningServiceCreateHolderProcedure:
			provisioningServiceCreateHolderHandler.ServeHTTP(w, r)
		case ProvisioningServiceCreateWalletProcedure:
			provisioningServiceCreateWalletHandler.ServeHTTP(w, r)
		case ProvisioningServiceCreateAccountProcedure:
			provisioningServiceCreateAccountHandler.ServeHTTP(w, r)
		case ProvisioningServiceGetWalletBalancesProcedure:
			provisioningServiceGetWalletBalancesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProvisioningServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProvisioningServiceHandler struct{}

func (UnimplementedProvisioningServiceHandler) CreateAsset(context.Context, *connect.Request[v1.CreateAssetRequest]) (*connect.Response[v1.Asset], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.ProvisioningService.CreateAsset is not implemented"))
}

func (UnimplementedProvisioningServiceHandler) ListAssets(context.Context, *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.ProvisioningService.ListAssets is not implemented"))
}

func (UnimplementedProvisioningServiceHandler) CreateHolder(context.Context, *connect.Request[v1.CreateHolderRequest]) (*connect.Response[v1.Holder], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.ProvisioningService.CreateHolder is not implemented"))
}

func (UnimplementedProvisioningServiceHandler) CreateWallet(context.Context, *connect.Request[v1.CreateWalletRequest]) (*connect.Response[v1.Wallet], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.ProvisioningService.CreateWallet is not implemented"))
}

func (UnimplementedProvisioningServiceHandler) CreateAccount(context.Context, *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.Account], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.ProvisioningService.CreateAccount is not implemented"))
}

func (UnimplementedProvisioningServiceHandler) GetWalletBalances(context.Context, *connect.Request[v1.GetWalletBalancesRequest]) (*connect.Response[v1.GetWalletBalancesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ledger.v1.ProvisioningService.GetWalletBalances is not implemented"))
}
