// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package store

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, wallet_id, asset_id, allow_negative)
VALUES ($1, $2, $3, $4)
RETURNING id, wallet_id, asset_id, allow_negative, created_at
`

type CreateAccountParams struct {
	ID            string
	WalletID      string
	AssetID       string
	AllowNegative bool
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.WalletID,
		arg.AssetID,
		arg.AllowNegative,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AssetID,
		&i.AllowNegative,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, wallet_id, asset_id, allow_negative, created_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AssetID,
		&i.AllowNegative,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByWalletAsset = `-- name: GetAccountByWalletAsset :one
SELECT id, wallet_id, asset_id, allow_negative, created_at
FROM accounts
WHERE wallet_id = $1 AND asset_id = $2
`

type GetAccountByWalletAssetParams struct {
	WalletID string
	AssetID  string
}

func (q *Queries) GetAccountByWalletAsset(ctx context.Context, arg GetAccountByWalletAssetParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByWalletAsset, arg.WalletID, arg.AssetID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AssetID,
		&i.AllowNegative,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsByWallet = `-- name: ListAccountsByWallet :many
SELECT id, wallet_id, asset_id, allow_negative, created_at
FROM accounts
WHERE wallet_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListAccountsByWallet(ctx context.Context, walletID string) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AssetID,
			&i.AllowNegative,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
