// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package store

import (
	"context"
)

const getAsset = `-- name: GetAsset :one
SELECT id, code, precision, metadata, created_at
FROM assets
WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Precision,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
