// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTransactionByReference = `-- name: GetTransactionByReference :one
SELECT id, idempotency_key, reference, status, metadata, created_at, posted_at, voided_at
FROM transactions
WHERE reference = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Provider references (e.g. a Stripe charge ID) are indexed but not
// unique per the schema: a reference may legitimately repeat across a
// charge and its refund. The lookup returns the most recent match —
// reconciliation callers that need the full set get it via ListWallet
// or a future filter.
func (q *Queries) GetTransactionByReference(ctx context.Context, reference pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByReference, reference)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.PostedAt,
		&i.VoidedAt,
	)
	return i, err
}

const listAccountEntries = `-- name: ListAccountEntries :many

SELECT id, transaction_id, account_id, amount, created_at
FROM entries
WHERE account_id = $1
ORDER BY created_at, id
LIMIT $2 OFFSET $3
`

type ListAccountEntriesParams struct {
	AccountID string
	Limit     int32
	Offset    int32
}

// Audit and lookup reads (ticket #6). These queries never mutate state;
// they back the AuditService list/lookup endpoints. Wallet transaction
// listing is not status-scoped: it returns every status (posted, pending,
// voided) unless the caller passes an exact status filter.
// One account's complete movement history, chronological. The caller
// passes limit = page_size + 1 so it can detect a further page without a
// COUNT query, then trims the extra row.
func (q *Queries) ListAccountEntries(ctx context.Context, arg ListAccountEntriesParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listAccountEntries, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT t.id, t.idempotency_key, t.reference, t.status, t.metadata, t.created_at, t.posted_at, t.voided_at
FROM transactions t
WHERE ($1::text IS NULL OR t.status = $1)
  AND EXISTS (
      SELECT 1
      FROM entries e
      JOIN accounts a ON a.id = e.account_id
      WHERE e.transaction_id = t.id
        AND a.wallet_id = $2
  )
ORDER BY t.created_at, t.id
LIMIT $4 OFFSET $3
`

type ListWalletTransactionsParams struct {
	Status   pgtype.Text
	WalletID string
	Offset   int32
	Limit    int32
}

// Every transaction that touches any account of the wallet — of any
// status by default, or exactly the requested status when one is passed.
// A transaction debiting one wallet account and crediting another of the
// same wallet still appears exactly once (EXISTS, not a join).
func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions,
		arg.Status,
		arg.WalletID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Reference,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.PostedAt,
			&i.VoidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
