// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balances.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createBalance = `-- name: CreateBalance :exec
INSERT INTO balances (account_id)
VALUES ($1)
`

func (q *Queries) CreateBalance(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, createBalance, accountID)
	return err
}

const getWalletBalances = `-- name: GetWalletBalances :many
SELECT a.id, a.wallet_id, a.asset_id, a.allow_negative, a.created_at, b.posted, b.pending
FROM accounts a
JOIN balances b ON b.account_id = a.id
WHERE a.wallet_id = $1
ORDER BY a.created_at, a.id
`

type GetWalletBalancesRow struct {
	ID            string
	WalletID      string
	AssetID       string
	AllowNegative bool
	CreatedAt     pgtype.Timestamptz
	Posted        decimal.Decimal
	Pending       decimal.Decimal
}

func (q *Queries) GetWalletBalances(ctx context.Context, walletID string) ([]GetWalletBalancesRow, error) {
	rows, err := q.db.Query(ctx, getWalletBalances, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWalletBalancesRow
	for rows.Next() {
		var i GetWalletBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AssetID,
			&i.AllowNegative,
			&i.CreatedAt,
			&i.Posted,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalance = `-- name: LockBalance :one
SELECT account_id, posted, pending, updated_at
FROM balances
WHERE account_id = $1
FOR UPDATE
`

func (q *Queries) LockBalance(ctx context.Context, accountID string) (Balance, error) {
	row := q.db.QueryRow(ctx, lockBalance, accountID)
	var i Balance
	err := row.Scan(
		&i.AccountID,
		&i.Posted,
		&i.Pending,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBalancePosted = `-- name: UpdateBalancePosted :exec
UPDATE balances
SET posted = posted + $2, updated_at = now()
WHERE account_id = $1
`

type UpdateBalancePostedParams struct {
	AccountID string
	Posted    decimal.Decimal
}

func (q *Queries) UpdateBalancePosted(ctx context.Context, arg UpdateBalancePostedParams) error {
	_, err := q.db.Exec(ctx, updateBalancePosted, arg.AccountID, arg.Posted)
	return err
}
