// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createEntry = `-- name: CreateEntry :exec
INSERT INTO entries (id, transaction_id, account_id, amount)
VALUES ($1, $2, $3, $4)
`

type CreateEntryParams struct {
	ID            pgtype.UUID
	TransactionID pgtype.UUID
	AccountID     string
	Amount        decimal.Decimal
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) error {
	_, err := q.db.Exec(ctx, createEntry,
		arg.ID,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
	)
	return err
}

const getEntriesByTransaction = `-- name: GetEntriesByTransaction :many
SELECT id, transaction_id, account_id, amount, created_at
FROM entries
WHERE transaction_id = $1
ORDER BY created_at, id
`

func (q *Queries) GetEntriesByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, getEntriesByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
