// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holders.sql

package store

import (
	"context"
)

const createHolder = `-- name: CreateHolder :one
INSERT INTO holders (id, type, external_ref, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, type, external_ref, metadata, created_at
`

type CreateHolderParams struct {
	ID          string
	Type        string
	ExternalRef string
	Metadata    []byte
}

func (q *Queries) CreateHolder(ctx context.Context, arg CreateHolderParams) (Holder, error) {
	row := q.db.QueryRow(ctx, createHolder,
		arg.ID,
		arg.Type,
		arg.ExternalRef,
		arg.Metadata,
	)
	var i Holder
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ExternalRef,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getHolder = `-- name: GetHolder :one
SELECT id, type, external_ref, metadata, created_at
FROM holders
WHERE id = $1
`

func (q *Queries) GetHolder(ctx context.Context, id string) (Holder, error) {
	row := q.db.QueryRow(ctx, getHolder, id)
	var i Holder
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ExternalRef,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
