// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID            string
	WalletID      string
	AssetID       string
	AllowNegative bool
	CreatedAt     pgtype.Timestamptz
}

type Asset struct {
	ID        string
	Code      string
	Precision int32
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type Balance struct {
	AccountID string
	Posted    decimal.Decimal
	Pending   decimal.Decimal
	UpdatedAt pgtype.Timestamptz
}

type Entry struct {
	ID            pgtype.UUID
	TransactionID pgtype.UUID
	AccountID     string
	Amount        decimal.Decimal
	CreatedAt     pgtype.Timestamptz
}

type Holder struct {
	ID          string
	Type        string
	ExternalRef string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}

type Transaction struct {
	ID             pgtype.UUID
	IdempotencyKey string
	Reference      pgtype.Text
	Status         string
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
	PostedAt       pgtype.Timestamptz
	VoidedAt       pgtype.Timestamptz
}

type Wallet struct {
	ID        string
	HolderID  string
	Name      string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}
