// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, idempotency_key, reference, status, posted_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, idempotency_key, reference, status, metadata, created_at, posted_at, voided_at
`

type CreateTransactionParams struct {
	ID             pgtype.UUID
	IdempotencyKey string
	Reference      pgtype.Text
	Status         string
	PostedAt       pgtype.Timestamptz
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.IdempotencyKey,
		arg.Reference,
		arg.Status,
		arg.PostedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.PostedAt,
		&i.VoidedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, idempotency_key, reference, status, metadata, created_at, posted_at, voided_at
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.PostedAt,
		&i.VoidedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, idempotency_key, reference, status, metadata, created_at, posted_at, voided_at
FROM transactions
WHERE idempotency_key = $1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.PostedAt,
		&i.VoidedAt,
	)
	return i, err
}

const lockTransaction = `-- name: LockTransaction :one
SELECT id, idempotency_key, reference, status, metadata, created_at, posted_at, voided_at
FROM transactions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, lockTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.PostedAt,
		&i.VoidedAt,
	)
	return i, err
}

const markTransactionPosted = `-- name: MarkTransactionPosted :one
UPDATE transactions
SET status = 'posted', posted_at = now()
WHERE id = $1
RETURNING id, idempotency_key, reference, status, metadata, created_at, posted_at, voided_at
`

func (q *Queries) MarkTransactionPosted(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionPosted, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.PostedAt,
		&i.VoidedAt,
	)
	return i, err
}

const markTransactionVoided = `-- name: MarkTransactionVoided :one
UPDATE transactions
SET status = 'voided', voided_at = now()
WHERE id = $1
RETURNING id, idempotency_key, reference, status, metadata, created_at, posted_at, voided_at
`

func (q *Queries) MarkTransactionVoided(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionVoided, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.PostedAt,
		&i.VoidedAt,
	)
	return i, err
}
