// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package store

import (
	"context"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (id, holder_id, name, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, holder_id, name, metadata, created_at
`

type CreateWalletParams struct {
	ID       string
	HolderID string
	Name     string
	Metadata []byte
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.ID,
		arg.HolderID,
		arg.Name,
		arg.Metadata,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.HolderID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, holder_id, name, metadata, created_at
FROM wallets
WHERE id = $1
`

func (q *Queries) GetWallet(ctx context.Context, id string) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.HolderID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
