// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ledger/v1/audit.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: the account whose complete movement history is listed.
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PageSize      uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageOffset    uint32 `protobuf:"varint,3,opt,name=page_offset,json=pageOffset,proto3" json:"page_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_ledger_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *ListEntriesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListEntriesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEntriesRequest) GetPageOffset() uint32 {
	if x != nil {
		return x.PageOffset
	}
	return 0
}

type ListEntriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chronological (created_at, id) page of the account's immutable
	// entries. Running totals are derivable by accumulating the signed
	// amounts in order.
	Entries []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Present only while a further page exists.
	NextPageOffset *uint32 `protobuf:"varint,2,opt,name=next_page_offset,json=nextPageOffset,proto3,oneof" json:"next_page_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_ledger_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEntriesResponse) GetNextPageOffset() uint32 {
	if x != nil && x.NextPageOffset != nil {
		return *x.NextPageOffset
	}
	return 0
}

type ListWalletTransactionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: the wallet whose accounts' transactions are listed.
	WalletId   string `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	PageSize   uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageOffset uint32 `protobuf:"varint,3,opt,name=page_offset,json=pageOffset,proto3" json:"page_offset,omitempty"`
	// Optional: filter to exactly this transaction status. Unset lists
	// transactions of every status — posted, pending, and voided — so
	// reconciliation sees the complete journal, not only settled movements.
	Status        *TransactionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=ledger.v1.TransactionStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletTransactionsRequest) Reset() {
	*x = ListWalletTransactionsRequest{}
	mi := &file_ledger_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletTransactionsRequest) ProtoMessage() {}

func (x *ListWalletTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListWalletTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *ListWalletTransactionsRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ListWalletTransactionsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWalletTransactionsRequest) GetPageOffset() uint32 {
	if x != nil {
		return x.PageOffset
	}
	return 0
}

func (x *ListWalletTransactionsRequest) GetStatus() TransactionStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

type ListWalletTransactionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chronological (created_at, id) page of every transaction touching any
	// account of the wallet, of any status unless the request filtered by
	// status, entries included. A transaction moving value between two
	// accounts of the same wallet appears exactly once.
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Present only while a further page exists.
	NextPageOffset *uint32 `protobuf:"varint,2,opt,name=next_page_offset,json=nextPageOffset,proto3,oneof" json:"next_page_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListWalletTransactionsResponse) Reset() {
	*x = ListWalletTransactionsResponse{}
	mi := &file_ledger_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletTransactionsResponse) ProtoMessage() {}

func (x *ListWalletTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListWalletTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *ListWalletTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListWalletTransactionsResponse) GetNextPageOffset() uint32 {
	if x != nil && x.NextPageOffset != nil {
		return *x.NextPageOffset
	}
	return 0
}

type GetTransactionByIdempotencyKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: the client-supplied key of the original write. Idempotency
	// keys are unique, so the match is exact.
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTransactionByIdempotencyKeyRequest) Reset() {
	*x = GetTransactionByIdempotencyKeyRequest{}
	mi := &file_ledger_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByIdempotencyKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByIdempotencyKeyRequest) ProtoMessage() {}

func (x *GetTransactionByIdempotencyKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByIdempotencyKeyRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByIdempotencyKeyRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_audit_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionByIdempotencyKeyRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetTransactionByReferenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: the provider reference (e.g. a Stripe charge ID). The
	// schema indexes but does not unique this column — a charge and its
	// refund may share a reference — so the lookup returns the most
	// recently created matching transaction, or not-found when none
	// exists.
	Reference     string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByReferenceRequest) Reset() {
	*x = GetTransactionByReferenceRequest{}
	mi := &file_ledger_v1_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByReferenceRequest) ProtoMessage() {}

func (x *GetTransactionByReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByReferenceRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByReferenceRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_audit_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionByReferenceRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

var File_ledger_v1_audit_proto protoreflect.FileDescriptor

const file_ledger_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x15ledger/v1/audit.proto\x12\tledger.v1\x1a\x17ledger/v1/posting.proto\"q\n" +
	"\x12ListEntriesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1f\n" +
	"\vpage_offset\x18\x03 \x01(\rR\n" +
	"pageOffset\"\x85\x01\n" +
	"\x13ListEntriesResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.ledger.v1.EntryR\aentries\x12-\n" +
	"\x10next_page_offset\x18\x02 \x01(\rH\x00R\x0enextPageOffset\x88\x01\x01B\x13\n" +
	"\x11_next_page_offset\"\xc0\x01\n" +
	"\x1dListWalletTransactionsRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1f\n" +
	"\vpage_offset\x18\x03 \x01(\rR\n" +
	"pageOffset\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.ledger.v1.TransactionStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\xa0\x01\n" +
	"\x1eListWalletTransactionsResponse\x12:\n" +
	"\ftransactions\x18\x01 \x03(\v2\x16.ledger.v1.TransactionR\ftransactions\x12-\n" +
	"\x10next_page_offset\x18\x02 \x01(\rH\x00R\x0enextPageOffset\x88\x01\x01B\x13\n" +
	"\x11_next_page_offset\"P\n" +
	"%GetTransactionByIdempotencyKeyRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\"@\n" +
	" GetTransactionByReferenceRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference2\x99\x03\n" +
	"\fAuditService\x12L\n" +
	"\vListEntries\x12\x1d.ledger.v1.ListEntriesRequest\x1a\x1e.ledger.v1.ListEntriesResponse\x12m\n" +
	"\x16ListWalletTransactions\x12(.ledger.v1.ListWalletTransactionsRequest\x1a).ledger.v1.ListWalletTransactionsResponse\x12j\n" +
	"\x1eGetTransactionByIdempotencyKey\x120.ledger.v1.GetTransactionByIdempotencyKeyRequest\x1a\x16.ledger.v1.Transaction\x12`\n" +
	"\x19GetTransactionByReference\x12+.ledger.v1.GetTransactionByReferenceRequest\x1a\x16.ledger.v1.TransactionB\x98\x01\n" +
	"\rcom.ledger.v1B\n" +
	"AuditProtoP\x01Z6github.com/use-fabrica/ledger/proto/ledger/v1;ledgerv1\xa2\x02\x03LXX\xaa\x02\tLedger.V1\xca\x02\tLedger\\V1\xe2\x02\x15Ledger\\V1\\GPBMetadata\xea\x02\n" +
	"Ledger::V1b\x06proto3"

var (
	file_ledger_v1_audit_proto_rawDescOnce sync.Once
	file_ledger_v1_audit_proto_rawDescData []byte
)

func file_ledger_v1_audit_proto_rawDescGZIP() []byte {
	file_ledger_v1_audit_proto_rawDescOnce.Do(func() {
		file_ledger_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_audit_proto_rawDesc), len(file_ledger_v1_audit_proto_rawDesc)))
	})
	return file_ledger_v1_audit_proto_rawDescData
}

var file_ledger_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ledger_v1_audit_proto_goTypes = []any{
	(*ListEntriesRequest)(nil),                    // 0: ledger.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil),                   // 1: ledger.v1.ListEntriesResponse
	(*ListWalletTransactionsRequest)(nil),         // 2: ledger.v1.ListWalletTransactionsRequest
	(*ListWalletTransactionsResponse)(nil),        // 3: ledger.v1.ListWalletTransactionsResponse
	(*GetTransactionByIdempotencyKeyRequest)(nil), // 4: ledger.v1.GetTransactionByIdempotencyKeyRequest
	(*GetTransactionByReferenceRequest)(nil),      // 5: ledger.v1.GetTransactionByReferenceRequest
	(*Entry)(nil),                                 // 6: ledger.v1.Entry
	(TransactionStatus)(0),                        // 7: ledger.v1.TransactionStatus
	(*Transaction)(nil),                           // 8: ledger.v1.Transaction
}
var file_ledger_v1_audit_proto_depIdxs = []int32{
	6, // 0: ledger.v1.ListEntriesResponse.entries:type_name -> ledger.v1.Entry
	7, // 1: ledger.v1.ListWalletTransactionsRequest.status:type_name -> ledger.v1.TransactionStatus
	8, // 2: ledger.v1.ListWalletTransactionsResponse.transactions:type_name -> ledger.v1.Transaction
	0, // 3: ledger.v1.AuditService.ListEntries:input_type -> ledger.v1.ListEntriesRequest
	2, // 4: ledger.v1.AuditService.ListWalletTransactions:input_type -> ledger.v1.ListWalletTransactionsRequest
	4, // 5: ledger.v1.AuditService.GetTransactionByIdempotencyKey:input_type -> ledger.v1.GetTransactionByIdempotencyKeyRequest
	5, // 6: ledger.v1.AuditService.GetTransactionByReference:input_type -> ledger.v1.GetTransactionByReferenceRequest
	1, // 7: ledger.v1.AuditService.ListEntries:output_type -> ledger.v1.ListEntriesResponse
	3, // 8: ledger.v1.AuditService.ListWalletTransactions:output_type -> ledger.v1.ListWalletTransactionsResponse
	8, // 9: ledger.v1.AuditService.GetTransactionByIdempotencyKey:output_type -> ledger.v1.Transaction
	8, // 10: ledger.v1.AuditService.GetTransactionByReference:output_type -> ledger.v1.Transaction
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ledger_v1_audit_proto_init() }
func file_ledger_v1_audit_proto_init() {
	if File_ledger_v1_audit_proto != nil {
		return
	}
	file_ledger_v1_posting_proto_init()
	file_ledger_v1_audit_proto_msgTypes[1].OneofWrappers = []any{}
	file_ledger_v1_audit_proto_msgTypes[2].OneofWrappers = []any{}
	file_ledger_v1_audit_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_audit_proto_rawDesc), len(file_ledger_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_audit_proto_goTypes,
		DependencyIndexes: file_ledger_v1_audit_proto_depIdxs,
		MessageInfos:      file_ledger_v1_audit_proto_msgTypes,
	}.Build()
	File_ledger_v1_audit_proto = out.File
	file_ledger_v1_audit_proto_goTypes = nil
	file_ledger_v1_audit_proto_depIdxs = nil
}
