// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ledger/v1/health.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServingStatus mirrors the gRPC health protocol states.
type ServingStatus int32

const (
	ServingStatus_SERVING_STATUS_UNSPECIFIED ServingStatus = 0
	ServingStatus_SERVING                    ServingStatus = 1
	ServingStatus_NOT_SERVING                ServingStatus = 2
)

// Enum value maps for ServingStatus.
var (
	ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING":                    1,
		"NOT_SERVING":                2,
	}
)

func (x ServingStatus) Enum() *ServingStatus {
	p := new(ServingStatus)
	*p = x
	return p
}

func (x ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_v1_health_proto_enumTypes[0].Descriptor()
}

func (ServingStatus) Type() protoreflect.EnumType {
	return &file_ledger_v1_health_proto_enumTypes[0]
}

func (x ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServingStatus.Descriptor instead.
func (ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_ledger_v1_health_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServingStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=ledger.v1.ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_ledger_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckResponse) GetStatus() ServingStatus {
	if x != nil {
		return x.Status
	}
	return ServingStatus_SERVING_STATUS_UNSPECIFIED
}

var File_ledger_v1_health_proto protoreflect.FileDescriptor

const file_ledger_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/health.proto\x12\tledger.v1\x1a\x1bgoogle/protobuf/empty.proto\"G\n" +
	"\x13HealthCheckResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.ledger.v1.ServingStatusR\x06status*M\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xa2\x01\n" +
	"\rHealthService\x12G\n" +
	"\rCheckLiveness\x12\x16.google.protobuf.Empty\x1a\x1e.ledger.v1.HealthCheckResponse\x12H\n" +
	"\x0eCheckReadiness\x12\x16.google.protobuf.Empty\x1a\x1e.ledger.v1.HealthCheckResponseB\x99\x01\n" +
	"\rcom.ledger.v1B\vHealthProtoP\x01Z6github.com/use-fabrica/ledger/proto/ledger/v1;ledgerv1\xa2\x02\x03LXX\xaa\x02\tLedger.V1\xca\x02\tLedger\\V1\xe2\x02\x15Ledger\\V1\\GPBMetadata\xea\x02\n" +
	"Ledger::V1b\x06proto3"

var (
	file_ledger_v1_health_proto_rawDescOnce sync.Once
	file_ledger_v1_health_proto_rawDescData []byte
)

func file_ledger_v1_health_proto_rawDescGZIP() []byte {
	file_ledger_v1_health_proto_rawDescOnce.Do(func() {
		file_ledger_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_health_proto_rawDesc), len(file_ledger_v1_health_proto_rawDesc)))
	})
	return file_ledger_v1_health_proto_rawDescData
}

var file_ledger_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ledger_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ledger_v1_health_proto_goTypes = []any{
	(ServingStatus)(0),          // 0: ledger.v1.ServingStatus
	(*HealthCheckResponse)(nil), // 1: ledger.v1.HealthCheckResponse
	(*emptypb.Empty)(nil),       // 2: google.protobuf.Empty
}
var file_ledger_v1_health_proto_depIdxs = []int32{
	0, // 0: ledger.v1.HealthCheckResponse.status:type_name -> ledger.v1.ServingStatus
	2, // 1: ledger.v1.HealthService.CheckLiveness:input_type -> google.protobuf.Empty
	2, // 2: ledger.v1.HealthService.CheckReadiness:input_type -> google.protobuf.Empty
	1, // 3: ledger.v1.HealthService.CheckLiveness:output_type -> ledger.v1.HealthCheckResponse
	1, // 4: ledger.v1.HealthService.CheckReadiness:output_type -> ledger.v1.HealthCheckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ledger_v1_health_proto_init() }
func file_ledger_v1_health_proto_init() {
	if File_ledger_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_health_proto_rawDesc), len(file_ledger_v1_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_health_proto_goTypes,
		DependencyIndexes: file_ledger_v1_health_proto_depIdxs,
		EnumInfos:         file_ledger_v1_health_proto_enumTypes,
		MessageInfos:      file_ledger_v1_health_proto_msgTypes,
	}.Build()
	File_ledger_v1_health_proto = out.File
	file_ledger_v1_health_proto_goTypes = nil
	file_ledger_v1_health_proto_depIdxs = nil
}
