// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ledger/v1/provisioning.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HolderType mirrors the holders.type CHECK constraint. The ledger never
// stores identity data: a holder is just the host app's external reference
// plus its role.
type HolderType int32

const (
	HolderType_HOLDER_TYPE_UNSPECIFIED HolderType = 0
	HolderType_HOLDER_TYPE_USER        HolderType = 1
	HolderType_HOLDER_TYPE_SYSTEM      HolderType = 2
	HolderType_HOLDER_TYPE_PROVIDER    HolderType = 3
)

// Enum value maps for HolderType.
var (
	HolderType_name = map[int32]string{
		0: "HOLDER_TYPE_UNSPECIFIED",
		1: "HOLDER_TYPE_USER",
		2: "HOLDER_TYPE_SYSTEM",
		3: "HOLDER_TYPE_PROVIDER",
	}
	HolderType_value = map[string]int32{
		"HOLDER_TYPE_UNSPECIFIED": 0,
		"HOLDER_TYPE_USER":        1,
		"HOLDER_TYPE_SYSTEM":      2,
		"HOLDER_TYPE_PROVIDER":    3,
	}
)

func (x HolderType) Enum() *HolderType {
	p := new(HolderType)
	*p = x
	return p
}

func (x HolderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HolderType) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_v1_provisioning_proto_enumTypes[0].Descriptor()
}

func (HolderType) Type() protoreflect.EnumType {
	return &file_ledger_v1_provisioning_proto_enumTypes[0]
}

func (x HolderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HolderType.Descriptor instead.
func (HolderType) EnumDescriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{0}
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Precision     int32                  `protobuf:"varint,3,opt,name=precision,proto3" json:"precision,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Asset) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Asset) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Holder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          HolderType             `protobuf:"varint,2,opt,name=type,proto3,enum=ledger.v1.HolderType" json:"type,omitempty"`
	ExternalRef   string                 `protobuf:"bytes,3,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holder) Reset() {
	*x = Holder{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holder) ProtoMessage() {}

func (x *Holder) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holder.ProtoReflect.Descriptor instead.
func (*Holder) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{1}
}

func (x *Holder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Holder) GetType() HolderType {
	if x != nil {
		return x.Type
	}
	return HolderType_HOLDER_TYPE_UNSPECIFIED
}

func (x *Holder) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *Holder) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Holder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HolderId      string                 `protobuf:"bytes,2,opt,name=holder_id,json=holderId,proto3" json:"holder_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{2}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetHolderId() string {
	if x != nil {
		return x.HolderId
	}
	return ""
}

func (x *Wallet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wallet) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Wallet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	AllowNegative bool                   `protobuf:"varint,4,opt,name=allow_negative,json=allowNegative,proto3" json:"allow_negative,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *Account) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Account) GetAllowNegative() bool {
	if x != nil {
		return x.AllowNegative
	}
	return false
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Precision     int32                  `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAssetRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateAssetRequest) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *CreateAssetRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{5}
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{6}
}

func (x *ListAssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type CreateHolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          HolderType             `protobuf:"varint,1,opt,name=type,proto3,enum=ledger.v1.HolderType" json:"type,omitempty"`
	ExternalRef   string                 `protobuf:"bytes,2,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHolderRequest) Reset() {
	*x = CreateHolderRequest{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHolderRequest) ProtoMessage() {}

func (x *CreateHolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHolderRequest.ProtoReflect.Descriptor instead.
func (*CreateHolderRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{7}
}

func (x *CreateHolderRequest) GetType() HolderType {
	if x != nil {
		return x.Type
	}
	return HolderType_HOLDER_TYPE_UNSPECIFIED
}

func (x *CreateHolderRequest) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *CreateHolderRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HolderId      string                 `protobuf:"bytes,1,opt,name=holder_id,json=holderId,proto3" json:"holder_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{8}
}

func (x *CreateWalletRequest) GetHolderId() string {
	if x != nil {
		return x.HolderId
	}
	return ""
}

func (x *CreateWalletRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWalletRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateAccountRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WalletId string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AssetId  string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// allow_negative defaults to false when unset: user accounts may not
	// overdraw. Reserved for system accounts.
	AllowNegative *bool `protobuf:"varint,3,opt,name=allow_negative,json=allowNegative,proto3,oneof" json:"allow_negative,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAccountRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *CreateAccountRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CreateAccountRequest) GetAllowNegative() bool {
	if x != nil && x.AllowNegative != nil {
		return *x.AllowNegative
	}
	return false
}

type GetWalletBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalancesRequest) Reset() {
	*x = GetWalletBalancesRequest{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalancesRequest) ProtoMessage() {}

func (x *GetWalletBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetWalletBalancesRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{10}
}

func (x *GetWalletBalancesRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

// AccountBalance is one account of the wallet with its materialized
// balances. Amounts are decimal strings (e.g. "1234.56") in the account's
// asset precision, matching shopspring/decimal serialization.
type AccountBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Posted        string                 `protobuf:"bytes,2,opt,name=posted,proto3" json:"posted,omitempty"`
	Pending       string                 `protobuf:"bytes,3,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBalance) Reset() {
	*x = AccountBalance{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalance) ProtoMessage() {}

func (x *AccountBalance) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalance.ProtoReflect.Descriptor instead.
func (*AccountBalance) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{11}
}

func (x *AccountBalance) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountBalance) GetPosted() string {
	if x != nil {
		return x.Posted
	}
	return ""
}

func (x *AccountBalance) GetPending() string {
	if x != nil {
		return x.Pending
	}
	return ""
}

type GetWalletBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Balances      []*AccountBalance      `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalancesResponse) Reset() {
	*x = GetWalletBalancesResponse{}
	mi := &file_ledger_v1_provisioning_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalancesResponse) ProtoMessage() {}

func (x *GetWalletBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_provisioning_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetWalletBalancesResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_provisioning_proto_rawDescGZIP(), []int{12}
}

func (x *GetWalletBalancesResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetWalletBalancesResponse) GetBalances() []*AccountBalance {
	if x != nil {
		return x.Balances
	}
	return nil
}

var File_ledger_v1_provisioning_proto protoreflect.FileDescriptor

const file_ledger_v1_provisioning_proto_rawDesc = "" +
	"\n" +
	"\x1cledger/v1/provisioning.proto\x12\tledger.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1c\n" +
	"\tprecision\x18\x03 \x01(\x05R\tprecision\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd6\x01\n" +
	"\x06Holder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.ledger.v1.HolderTypeR\x04type\x12!\n" +
	"\fexternal_ref\x18\x03 \x01(\tR\vexternalRef\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb9\x01\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tholder_id\x18\x02 \x01(\tR\bholderId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb3\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\tR\aassetId\x12%\n" +
	"\x0eallow_negative\x18\x04 \x01(\bR\rallowNegative\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"{\n" +
	"\x12CreateAssetRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\x05R\tprecision\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x13\n" +
	"\x11ListAssetsRequest\">\n" +
	"\x12ListAssetsResponse\x12(\n" +
	"\x06assets\x18\x01 \x03(\v2\x10.ledger.v1.AssetR\x06assets\"\x98\x01\n" +
	"\x13CreateHolderRequest\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.ledger.v1.HolderTypeR\x04type\x12!\n" +
	"\fexternal_ref\x18\x02 \x01(\tR\vexternalRef\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"{\n" +
	"\x13CreateWalletRequest\x12\x1b\n" +
	"\tholder_id\x18\x01 \x01(\tR\bholderId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x8d\x01\n" +
	"\x14CreateAccountRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12*\n" +
	"\x0eallow_negative\x18\x03 \x01(\bH\x00R\rallowNegative\x88\x01\x01B\x11\n" +
	"\x0f_allow_negative\"7\n" +
	"\x18GetWalletBalancesRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"p\n" +
	"\x0eAccountBalance\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.ledger.v1.AccountR\aaccount\x12\x16\n" +
	"\x06posted\x18\x02 \x01(\tR\x06posted\x12\x18\n" +
	"\apending\x18\x03 \x01(\tR\apending\"o\n" +
	"\x19GetWalletBalancesResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x125\n" +
	"\bbalances\x18\x02 \x03(\v2\x19.ledger.v1.AccountBalanceR\bbalances*q\n" +
	"\n" +
	"HolderType\x12\x1b\n" +
	"\x17HOLDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10HOLDER_TYPE_USER\x10\x01\x12\x16\n" +
	"\x12HOLDER_TYPE_SYSTEM\x10\x02\x12\x18\n" +
	"\x14HOLDER_TYPE_PROVIDER\x10\x032\xcc\x03\n" +
	"\x13ProvisioningService\x12>\n" +
	"\vCreateAsset\x12\x1d.ledger.v1.CreateAssetRequest\x1a\x10.ledger.v1.Asset\x12I\n" +
	"\n" +
	"ListAssets\x12\x1c.ledger.v1.ListAssetsRequest\x1a\x1d.ledger.v1.ListAssetsResponse\x12A\n" +
	"\fCreateHolder\x12\x1e.ledger.v1.CreateHolderRequest\x1a\x11.ledger.v1.Holder\x12A\n" +
	"\fCreateWallet\x12\x1e.ledger.v1.CreateWalletRequest\x1a\x11.ledger.v1.Wallet\x12D\n" +
	"\rCreateAccount\x12\x1f.ledger.v1.CreateAccountRequest\x1a\x12.ledger.v1.Account\x12^\n" +
	"\x11GetWalletBalances\x12#.ledger.v1.GetWalletBalancesRequest\x1a$.ledger.v1.GetWalletBalancesResponseB\x9f\x01\n" +
	"\rcom.ledger.v1B\x11ProvisioningProtoP\x01Z6github.com/use-fabrica/ledger/proto/ledger/v1;ledgerv1\xa2\x02\x03LXX\xaa\x02\tLedger.V1\xca\x02\tLedger\\V1\xe2\x02\x15Ledger\\V1\\GPBMetadata\xea\x02\n" +
	"Ledger::V1b\x06proto3"

var (
	file_ledger_v1_provisioning_proto_rawDescOnce sync.Once
	file_ledger_v1_provisioning_proto_rawDescData []byte
)

func file_ledger_v1_provisioning_proto_rawDescGZIP() []byte {
	file_ledger_v1_provisioning_proto_rawDescOnce.Do(func() {
		file_ledger_v1_provisioning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_provisioning_proto_rawDesc), len(file_ledger_v1_provisioning_proto_rawDesc)))
	})
	return file_ledger_v1_provisioning_proto_rawDescData
}

var file_ledger_v1_provisioning_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ledger_v1_provisioning_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ledger_v1_provisioning_proto_goTypes = []any{
	(HolderType)(0),                   // 0: ledger.v1.HolderType
	(*Asset)(nil),                     // 1: ledger.v1.Asset
	(*Holder)(nil),                    // 2: ledger.v1.Holder
	(*Wallet)(nil),                    // 3: ledger.v1.Wallet
	(*Account)(nil),                   // 4: ledger.v1.Account
	(*CreateAssetRequest)(nil),        // 5: ledger.v1.CreateAssetRequest
	(*ListAssetsRequest)(nil),         // 6: ledger.v1.ListAssetsRequest
	(*ListAssetsResponse)(nil),        // 7: ledger.v1.ListAssetsResponse
	(*CreateHolderRequest)(nil),       // 8: ledger.v1.CreateHolderRequest
	(*CreateWalletRequest)(nil),       // 9: ledger.v1.CreateWalletRequest
	(*CreateAccountRequest)(nil),      // 10: ledger.v1.CreateAccountRequest
	(*GetWalletBalancesRequest)(nil),  // 11: ledger.v1.GetWalletBalancesRequest
	(*AccountBalance)(nil),            // 12: ledger.v1.AccountBalance
	(*GetWalletBalancesResponse)(nil), // 13: ledger.v1.GetWalletBalancesResponse
	(*structpb.Struct)(nil),           // 14: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
}
var file_ledger_v1_provisioning_proto_depIdxs = []int32{
	14, // 0: ledger.v1.Asset.metadata:type_name -> google.protobuf.Struct
	15, // 1: ledger.v1.Asset.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: ledger.v1.Holder.type:type_name -> ledger.v1.HolderType
	14, // 3: ledger.v1.Holder.metadata:type_name -> google.protobuf.Struct
	15, // 4: ledger.v1.Holder.created_at:type_name -> google.protobuf.Timestamp
	14, // 5: ledger.v1.Wallet.metadata:type_name -> google.protobuf.Struct
	15, // 6: ledger.v1.Wallet.created_at:type_name -> google.protobuf.Timestamp
	15, // 7: ledger.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	14, // 8: ledger.v1.CreateAssetRequest.metadata:type_name -> google.protobuf.Struct
	1,  // 9: ledger.v1.ListAssetsResponse.assets:type_name -> ledger.v1.Asset
	0,  // 10: ledger.v1.CreateHolderRequest.type:type_name -> ledger.v1.HolderType
	14, // 11: ledger.v1.CreateHolderRequest.metadata:type_name -> google.protobuf.Struct
	14, // 12: ledger.v1.CreateWalletRequest.metadata:type_name -> google.protobuf.Struct
	4,  // 13: ledger.v1.AccountBalance.account:type_name -> ledger.v1.Account
	12, // 14: ledger.v1.GetWalletBalancesResponse.balances:type_name -> ledger.v1.AccountBalance
	5,  // 15: ledger.v1.ProvisioningService.CreateAsset:input_type -> ledger.v1.CreateAssetRequest
	6,  // 16: ledger.v1.ProvisioningService.ListAssets:input_type -> ledger.v1.ListAssetsRequest
	8,  // 17: ledger.v1.ProvisioningService.CreateHolder:input_type -> ledger.v1.CreateHolderRequest
	9,  // 18: ledger.v1.ProvisioningService.CreateWallet:input_type -> ledger.v1.CreateWalletRequest
	10, // 19: ledger.v1.ProvisioningService.CreateAccount:input_type -> ledger.v1.CreateAccountRequest
	11, // 20: ledger.v1.ProvisioningService.GetWalletBalances:input_type -> ledger.v1.GetWalletBalancesRequest
	1,  // 21: ledger.v1.ProvisioningService.CreateAsset:output_type -> ledger.v1.Asset
	7,  // 22: ledger.v1.ProvisioningService.ListAssets:output_type -> ledger.v1.ListAssetsResponse
	2,  // 23: ledger.v1.ProvisioningService.CreateHolder:output_type -> ledger.v1.Holder
	3,  // 24: ledger.v1.ProvisioningService.CreateWallet:output_type -> ledger.v1.Wallet
	4,  // 25: ledger.v1.ProvisioningService.CreateAccount:output_type -> ledger.v1.Account
	13, // 26: ledger.v1.ProvisioningService.GetWalletBalances:output_type -> ledger.v1.GetWalletBalancesResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_ledger_v1_provisioning_proto_init() }
func file_ledger_v1_provisioning_proto_init() {
	if File_ledger_v1_provisioning_proto != nil {
		return
	}
	file_ledger_v1_provisioning_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_provisioning_proto_rawDesc), len(file_ledger_v1_provisioning_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_provisioning_proto_goTypes,
		DependencyIndexes: file_ledger_v1_provisioning_proto_depIdxs,
		EnumInfos:         file_ledger_v1_provisioning_proto_enumTypes,
		MessageInfos:      file_ledger_v1_provisioning_proto_msgTypes,
	}.Build()
	File_ledger_v1_provisioning_proto = out.File
	file_ledger_v1_provisioning_proto_goTypes = nil
	file_ledger_v1_provisioning_proto_depIdxs = nil
}
